[package]
name = "client_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }

[workspace]
members = [
	"examples/chat"
]
